apiVersion: apps/v1
kind: Deployment
metadata:
  name: erjohnter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: erjohnter
  template:
    metadata:
      labels:
        app: erjohnter
    spec:
      containers:
      - image: okteto.dev/erjohnter:latest
        name: erjohnter
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "95dd0a18-22ac-42c8-aa44-930083b4eaad"
        - name: Vless_Path
          value: "/95dd0a18-22ac-42c8-aa44-930083b4eaad-vless"
        - name: Vmess_UUID
          value: "95dd0a18-22ac-42c8-aa44-930083b4eaad"
        - name: Vmess_Path
          value: "/95dd0a18-22ac-42c8-aa44-930083b4eaad-vmess"
        - name: Share_Path
          value: "/v2link"
